/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAgentEscrow {
  export type TaskStruct = {
    taskId: BytesLike;
    client: AddressLike;
    agentWallet: AddressLike;
    amount: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
    resultHash: BytesLike;
  };

  export type TaskStructOutput = [
    taskId: string,
    client: string,
    agentWallet: string,
    amount: bigint,
    status: bigint,
    createdAt: bigint,
    completedAt: bigint,
    resultHash: string
  ] & {
    taskId: string;
    client: string;
    agentWallet: string;
    amount: bigint;
    status: bigint;
    createdAt: bigint;
    completedAt: bigint;
    resultHash: string;
  };
}

export interface IAgentEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelTask"
      | "cancelTaskByOperator"
      | "completeTask"
      | "getTask"
      | "lockFunds"
      | "platformFeePercent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TaskCancelled"
      | "TaskCompleted"
      | "TaskCreated"
      | "TaskDisputed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTaskByOperator",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "lockFunds",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelTaskByOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [
    taskId: BytesLike,
    client: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    client: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    taskId: string;
    client: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    agentWallet: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    agentWallet: string,
    amount: bigint
  ];
  export interface OutputObject {
    taskId: string;
    agentWallet: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    client: AddressLike,
    agentWallet: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    client: string,
    agentWallet: string,
    amount: bigint
  ];
  export interface OutputObject {
    taskId: string;
    client: string;
    agentWallet: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDisputedEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAgentEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentEscrow;
  waitForDeployment(): Promise<this>;

  interface: IAgentEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  cancelTaskByOperator: TypedContractMethod<
    [taskId: BytesLike],
    [void],
    "nonpayable"
  >;

  completeTask: TypedContractMethod<
    [taskId: BytesLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [IAgentEscrow.TaskStructOutput],
    "view"
  >;

  lockFunds: TypedContractMethod<
    [taskId: BytesLike, agentWallet: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTaskByOperator"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<
    [taskId: BytesLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [IAgentEscrow.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockFunds"
  ): TypedContractMethod<
    [taskId: BytesLike, agentWallet: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDisputed"
  ): TypedContractEvent<
    TaskDisputedEvent.InputTuple,
    TaskDisputedEvent.OutputTuple,
    TaskDisputedEvent.OutputObject
  >;

  filters: {
    "TaskCancelled(bytes32,address,uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCompleted(bytes32,address,uint256)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(bytes32,address,address,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDisputed(bytes32)": TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
    TaskDisputed: TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
  };
}
